name: Test

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/test.yml'
  schedule:
    - cron:  '0 0 10 * *'
defaults:
  run:
    shell: bash
    working-directory: ./src
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
        
    - name: Build projects
      run: dotnet build

    - name: Run unit tests
      run: dotnet test